### ISSUE TITLE
UNRECOGNIZED FILE

### ISSUE THREAD

**Issue by rekatab** [RobertoMachorro/Moped#9] opened 2020-01-19 21:59 UTC
When opening an .txt-File, which can be edited with unix command vi, moped often opens the file and displaying "UNRECOGNIZED FILE" instead of displaying the file contents in plaintext.

**Comment by RobertoMachorro** [comment] 2020-01-19 23:28
Thanks for the feedback! Do you know if the file encoding is anything other than Unicode? Would it be possible for you to share one such file for testing/reproducing the issue?

**Comment by rekatab** [comment] 2020-01-20 12:19
I think, the problem is with some representations of german umlauts...
[test2.txt](https://github.com/RobertoMachorro/Moped/files/4086108/test2.txt)
[test3.txt](https://github.com/RobertoMachorro/Moped/files/4086109/test3.txt)

**Comment by RobertoMachorro** [comment] 2020-01-20 20:31
> I think, the problem is with some representations of german umlauts...
> [test2.txt](https://github.com/RobertoMachorro/Moped/files/4086108/test2.txt)
> [test3.txt](https://github.com/RobertoMachorro/Moped/files/4086109/test3.txt)

Thanks for sending. BBEdit is reporting their format to be in Western (Mac OS Roman) / Windows (CRLF) - both files. VIM does an on the fly conversion for me. You are probably correct in that the Umlauts are causing this. That said, they should load. I'll work on this, because Moped should still be able to load them (recognizes them as public.plain-text). Will keep you posted.

<img width="479" alt="image" src="https://user-images.githubusercontent.com/7190436/72755918-adcab700-3b99-11ea-8512-dbe996ae45cc.png">

**Comment by RobertoMachorro** [comment] 2020-01-22 03:15
Got a new build out for testing. It tries to do encoding detection in known macOS formats. It's not complete, but gives good mileage. Download [here](https://github.com/RobertoMachorro/Moped/releases/tag/1.5.2).

<img width="324" alt="image" src="https://user-images.githubusercontent.com/7190436/72862517-78a68d80-3c9b-11ea-9771-0273892417f7.png">

**Comment by RobertoMachorro** [comment] 2020-02-17 18:20
Research on the "right way" to detect encoding points to [NSString.stringEncoding](https://developer.apple.com/documentation/foundation/nsstring/1413576-stringencoding), however the API isn't returning accurate results. Going to go ahead and proceed with the trial/error method until this API gets fixed by Apple.

**Comment by RobertoMachorro** [comment] 2020-09-13 21:08
This was raised up to Apple Support, the short story is: there is no sure way to identify documents. When in doubt, ask the user, and that is exactly what BBEdit does when it doesn't recognize the encoding of a file.

For now the automated recognition seems to work, as of v1.6 of Moped. Closing issue.

**Closed by RobertoMachorro** 2020-09-13 21:08 UTC
